### ISSUE TITLE
Python proficiency 

### ISSUE THREAD

**Issue by Ixonblitz-MatOS** [sverigeunit/Chive-Programming-Language#1]
You decided to do the python interpreter(main.py) with if/elif/else statements for every part of the language and this is the least proficient way to be done because to interpret something towards the end, it will take longer, maybe instead use async/asyncio and have lists that they can iterate over and then have functions for those and instead of a list make it a dictionary. Ways that could work is
`for I in dictionary.keys:`

**Comment by Ixonblitz-MatOS** [comment]
Python doesn't have to be super slow if you use 3.11 it will have speed increase you need good programming though

**Comment by sverigeunit** [comment]
Yep. I see how this can take a long time. The c++ source code is the most optimized and it includes a dictionary and well done documented code. I am still working on it though. I am just going to close this because optimization will be worked on soon.

**Comment by Ixonblitz-MatOS** [comment]
Hey check the repo that I added I made a few versions using match case and iteration looping if you want an idea of what I thought you were missing, I was working on your javascript one as well

**Comment by Ixonblitz-MatOS** [comment]
feel free to use what I wrote just add credit comment at top if interested

**Comment by Ixonblitz-MatOS** [comment]
need any help with the c++?

**Comment by sverigeunit** [comment]
Ok. Thank you for helping I will check out the code and do testing on it. I am good with the c++.
