### ISSUE TITLE
Python programming 

### ISSUE THREAD

**Issue by Ixonblitz-MatOS** [sverigeunit/Chive-Programming-Language#2]
You decided to use semicolons on a lot of these lines why? Python doesn't use semicolons

**Comment by sverigeunit** [comment]
Hello. The python code was made with a ai tool that translated it from javascript then I modified it. The next release will include much more better styled code/

**Comment by Ixonblitz-MatOS** [comment]
I remade it, just copy mine and check to make sure it runs I got no errors but to be safe

**Comment by sverigeunit** [comment]
Ok I will check out the code. Thank you for helping.
