### ISSUE TITLE
regarding commit history 

### ISSUE THREAD

**Issue by Imshubh69** [sverigeunit/Chive-Programming-Language#3]
Hwy this is Shubh
I saw your project and noticed it's a awesome concept but when i saw your commit history it's kinda very childish if you don't mind please squash commits into one with `git rebase -i`
Or if you don't wanna do that just imporve your commit history in future

**Comment by maisonsmd** [comment]
@Imshubh69 the push.sh file should be mentioned too

**Comment by Imshubh69** [comment]
> @Imshubh69 the push.sh file should be mentioned too

I don't think you need that for cleaning commit history

**Comment by maisonsmd** [comment]
@Imshubh69 I mean the script is quite useless and it make the commit messages useless also. 

Just type what changes you made into the `git commit`, and sometimes you wont want to stage every files by `git add *`. Or you don't to push to another branch. You should have control to all them them.

The file gives a bad habit and a room for mistakes.

**Comment by sverigeunit** [comment]
Hey!! Thank you for pointing this out. I will work on making the commits more nice.
